do not preload hidden files and files in hidden folders
greenmail-mail-test/greenmail pull request #683
Opened 2024-02-09 11:34 UTC by An1s9n

Resolves #682

2024-02-11 18:57 UTC, marcelmay requested changes
Please do not remove the mentioned foo-bar and drafts folders. These make the test fail.

Otherwise looks good, thanks alot!

2024-02-11 18:57 UTC, marcelmay commented on greenmail-core/src/test/resources/preload/foo-bar@localhost/.keepme
Required for test to succeed, please do not delete this

2024-02-11 18:57 UTC, marcelmay commented on greenmail-core/src/test/resources/preload/drafts@localhost/Drafts/.keepme
Required for test to succeed, please do not delete this

2024-02-12 05:52 UTC, An1s9n commented on greenmail-core/src/test/resources/preload/foo-bar@localhost/.keepme
Yeah, my bad. Of course you are right, git does not track empty folders. Fixed that.

2024-02-12 05:52 UTC, An1s9n commented on greenmail-core/src/test/resources/preload/drafts@localhost/Drafts/.keepme
Yeah, my bad. Of course you are right, git does not track empty folders. Fixed that.

2024-02-12 19:26 UTC, merged